# Will notify when download speed or ping is below/above value

#automation:
# # - alias: Network error
#    trigger:
#        platform: numeric_state
#        entity_id: sensor.speedtest_download
#        below: 60
#        platform: numeric_state
#        entity_id: sensor.speedtest_ping
#        above: 20
#    action:
#      service: notify.telegram
#      data:
#        title: The weather
#        message: Right now you have {{ states("sensor.speedtest_download") } in download speed and {{ states("sensor.speedtest_ping") } in ping

