
homeassistant:
  packages: !include_dir_named packages

#ssl_cert: !secret ssl_cert
#ssl_key: !secret ssl_key
#base_url: home.tobiasakesson.com

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

updater:

discovery:

ios:

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 30000


#cloud:

#config:

#frontend:

#history:

#logbook:

#map:

#mobile_app:

#person:

#script:

#ssdp:

#sun:

#system_health:

#zeroconf:

#automation: !include automations.yaml
script: !include scripts.yaml
