homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:

config:

http:
    api_password: !secret http_password
#    base_url: !http_url
    ssl_certificate: !secret ssl_certificate
    ssl_key: !secret ssl_key

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

ios:

switch:
  - platform: wake_on_lan
    name: PC
    host: 192.168.1.224
    mac_address: "18-31-BF-BE-2F-97"

tts:
  - platform: google

# Philips hue
light: 
  - platform: hue
    host: 192.168.1.116

# Z-wave

zwave:
  usb_path: /dev/ttyACM0

# notifications until change to iphone

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid

script: !include scripts.yaml
