#
# Network
#

homeassistant:
  customize_glob:
    sensor.speedtest_download:
      friendly_name: Download speed
      icon: mdi:download
    sensor.speedtest_upload:
      friendly_name: Upload speed
      icon: mdi:upload
    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:timer

#Group for seeing network information in HA

#group:
#  network:
#    name: Network
#    entities:
#      - sensor.speedtest_download
#      - sensor.speedtest_upload
#      - sensor.speedtest_ping

#Sensor for the group above

sensor:
  - platform: speedtest
    monitored_conditions:
      - download
      - upload
      - ping
    hours:
      - 0
      - 6
      - 12
      - 18


# Will notify when download speed or ping is below/above value

#automation:
#  - alias: Network error
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.speedtest_download
#        below: 60
#      - platform: numeric_state
#        entity_id: sensor.speedtest_ping
#        above: 20
#    action:
#      service: notify.telegram
#      service:: notify.ios_tobias_iphone
#      data:
#        title: Network information.
#        message: 'You only have {{ states.sensor.speedtest_download.state }} in download speed and {{ states.sensor.speedtest_ping.state }} in ping'
