### Will turn on window light 30 minutes after sunset

automation: 
  - alias: "Sunset, lights on"
    trigger: 
      platform: sun
      event: sunset
      offset: "-00:30:00"
    action: 
      service: homeassistant.turn_on
      entity_id: switch.switch

### Will turn off window light 30 minutes before sunrise

  - alias: "Sunrise, lights off"
    trigger: 
      platform: sun
      event: sunrise
      offset: "+00:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.switch
