
#
# Weather
#

sensor:
  - platform: darksky
    api_key: !secret darksky_api
    units: si
    monitored_conditions:
      - summary
      - icon
      - temperature
      - temperature_high
      - temperature_low
      - hourly_summary
      - apparent_temperature
    forecast:
      - 0
    scan_interval:
      days: 0
      hours: 0
      minutes: 3
      seconds: 0

#
# On workdays will send current weather and expexted top temperature of the day.
#

automation: 
  - alias: Weather update
    trigger:
      - platform: time
        at: '07:10:00'
    condition:
      - condition: state
        entity_id: binary_sensor.workday
        state: 'on'
    action:
#      service: notify.telegram
      service: notify.ios_tobias_iphone
      data:
        title: Daily weather update
        message: 'Right now it is {{ states.sensor.dark_sky_summary.state }} and {{ states.sensor.dark_sky_temperature.state }} °C outside, the peak temp today will be {{ states.sensor.dark_sky_daytime_high_temperature_0d.state }} °C and the lowest is {{ states.sensor.dark_sky_overnight_low_temperature_0d.state }} °C '

