#
# Weather
#

sensor:
  - platform: darksky
    api_key: !secret darksky_api
    units: si
    monitored_conditions:
      - summary
      - icon
      - temperature
    update_interval:
      days: 0
      hours: 0
      minutes: 3
      seconds: 0

automation: 
  - alias: Weather update
    trigger:
      - platform: time
        at: '06:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.workday
        state: 'on'
    action:
      service: notify.telegram
      data:
        message: 'Right now it is {{ states.sensor.dark_sky_summary.state }} and {{ states.sensor.dark_sky_temperature.state }} °C outside'
